POST http://localhost:3333/events
Content-Type: application/json 
//cabeçalho
//informa o tipo de conteudo para a api

{
    "title": "Unite Summit",
    "details": "Um evento para quem é apaixonado por programação",
    "maximumAttendees": 100
}


###


POST http://localhost:3333/events/76f8d05c-5ad9-41f3-9d31-8180928cc31e/attendees
Content-Type: application/json 

{
    "name":"Arthur",
    "email":"arthuralt@gmail.com.br"
}