POST http://localhost:3333/events
Content-Type: application/json 
//cabeçalho
//informa o tipo de conteudo para a api

{
    "title":  2,
    "details": null,
    "maximumAttendees": 1
}


###


POST http://localhost:3333/events/e1afd391-a11a-4e3a-a09b-4b23938498ca/attendees
Content-Type: application/json 

{
    "name":"Arthur",
    "email":"arthur3@gmail.com.br"
}



###

GET http://localhost:3333/events/e1afd391-a11a-4e3a-a09b-4b23938498ca

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/4/check-in


###

GET http://localhost:3333/events/e1afd391-a11a-4e3a-a09b-4b23938498ca/attendees?query=arthur
